# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/chewc-jax',
                'doc_host': 'https://cjGO.github.io',
                'git_url': 'https://github.com/cjGO/chewc-jax',
                'lib_path': 'chewc_jax'},
  'syms': {'chewc_jax.core': {'chewc_jax.core.foo': ('core.html#foo', 'chewc_jax/core.py')}}}
